src/Presentation/Estate.MVC/Areas/Admin/Controllers/FeaturesController.cs
using Estate.Application.Abstractions.Services;
using Estate.Application.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Estate.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Moderator")]
    [AutoValidateAntiforgeryToken]
    public class FeaturesController : Controller
    {
        private readonly IFeaturesService _service;

        public FeaturesController(IFeaturesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(string? search, string? returnUrl, int order = 1, int page = 1)
        {
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return View(model: await _service.GetFilteredAsync(search, 10, page, order));
        }

        public async Task<IActionResult> DeletedItems(string? search, string? returnUrl, int order = 1, int page = 1)
        {
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return View(model: await _service.GetFilteredAsync(search, 10, page, order, true));
        }

        public IActionResult Create(string? returnUrl)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateFeaturesVM create, string? returnUrl)
        {
            bool result = await _service.CreateAsync(create, ModelState);
            if (!result)
            {
                return View(create);
            }
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int id, string? returnUrl)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View(await _service.UpdateAsync(id));
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, string? returnUrl, UpdateFeaturesVM update)
        {
            bool result = await _service.UpdatePostAsync(id, update, ModelState);
            if (!result)
            {
                return View(update);
            }
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> SoftDelete(int id, string? returnUrl)
        {
            await _service.SoftDeleteAsync(id);
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ReverseSoftDelete(int id, string? returnUrl)
        {
            await _service.ReverseSoftDeleteAsync(id);
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction(nameof(DeletedItems));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id, string? returnUrl)
        {
            await _service.DeleteAsync(id);
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction(nameof(DeletedItems));
        }

        public async Task<IActionResult> Detail(int id, string? returnUrl)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View(await _service.GetByIdAsync(id));
        }
    }
}

src/Presentation/Estate.MVC/Areas/Admin/Views/Features/Create.cshtml
@model CreateFeaturesVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Feature</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Features" asp-route-returnUrl="@ViewData["ReturnUrl"]" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

src/Presentation/Estate.MVC/Areas/Admin/Views/Features/DeletedItems.cshtml
@model PaginationVM<ItemFeaturesVM>

@{
    int count = (Model.CurrentPage - 1) * Model.Take;
}

<div class="d-flex justify-content-end">
    <div class="input-group mx-3">
        <form asp-action="DeletedItems" asp-controller="Features"
              asp-route-order="@Model.Order">
            <input type="text" class="form-control" placeholder="Search now" name="search" value="@(Model.Search == null? "":Model.Search)">
        </form>
    </div>
    <form asp-action="DeletedItems" asp-controller="Features"
          asp-route-order="@Model.Search" class="my-2 ">
        <select class="form-control form-control-sm rounded-1" onchange="this.form.submit()" name="Order">
            <option selected disabled>Sort by Default</option>
            <option value="1">Name</option>
            <option value="2">Created at</option>
            <option value="3">Name by Descending</option>
            <option value="4">Created at by Descending</option>
        </select>
    </form>
    <a asp-controller="Features" asp-action="Index" class="btn btn-success fw-bold fs-6 text-white w-25 m-2">Features</a>
</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deleted Features table</h4>
            <a asp-controller="Features" asp-action="Create" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-warning fw-bold fs-6 text-white">Create Feature</a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Products
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model.Items)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @item.Name
                                </td>
                                <td>
                                    @item.Products.Count
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Features" asp-route-id="@item.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-primary btn-info">
                                        <i class="mdi mdi-pencil text-white"></i>
                                    </a>
                                    @if (User.IsInRole(UserRoles.Admin.ToString()))
                                    {
                                        <a asp-action="ReverseSoftDelete" asp-controller="Features" asp-route-id="@item.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-secondary">
                                            <i class="mdi mdi-backup-restore text-white"></i>
                                        </a>
                                        <a asp-action="Delete" asp-controller="Features" asp-route-id="@item.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-danger btn-info">
                                            <i class="mdi mdi-delete-forever text-white"></i>
                                        </a>
                                    }
                                    <a asp-action="Detail" asp-controller="Features" asp-route-id="@item.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-primary">
                                        <i class="mdi mdi-open-in-new text-white"></i>
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(Model.CurrentPage <= 1 ? "disabled" : "")"><a class="page-link" asp-route-page="@(Model.CurrentPage -1)" asp-action="DeletedItems" asp-controller="Features">Previous</a></li>
                    @for (int i = 1; i <= Model.TotalPage; i++)
                    {
                        <li class="page-item @(Model.CurrentPage == i ? "disabled" : "")"><a asp-action="DeletedItems" asp-route-page="@i" asp-controller="Features" class="page-link">@i</a></li>
                    }
                    <li class="page-item @(Model.CurrentPage >= Model.TotalPage ? "disabled" : "")"><a class="page-link" asp-route-page="@(Model.CurrentPage +1)" asp-action="DeletedItems" asp-controller="Features">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

src/Presentation/Estate.MVC/Areas/Admin/Views/Features/Detail.cshtml
@model GetFeaturesVM

<div class="container">
    <h3 class="fw-bold m-3">@Model.Name Products</h3>
    <h4 class="fw-normal mx-5 my-3">Product Count: @Model.Products.Count</h4>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var product in Model.Products)
    {
        <div class="col">
            <div class="card bg-secondary">
                <img src="@product.Images.FirstOrDefault(pi => pi.IsPrimary == true).Url"
                     alt="@product.Name" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title text-white">Name: @product.Name</h5>
                    <p class="card-text text-white">Description: @product.Description</p>
                    <p class="card-text text-white">Price: $@product.Price</p>
                    <p class="card-text text-white">Area: @product.Area</p>
                    <p class="card-text text-white">Lot Size: @product.LotSize</p>

                    <p class="card-text text-white">Bedrooms: @product.Bedrooms</p>
                    <p class="card-text text-white">Bathrooms: @product.Bathrooms</p>
                    <p class="card-text text-white">Garages: @product.Garages</p>
                    <p class="card-text text-white">YearBuilt: @product.YearBuilt</p>
                    <p class="card-text text-white">Room Count: @product.RoomCount</p>
                    <p class="card-text text-white">Garages: @product.Garages</p>
                    @if (product.SchoolDistrict != null)
                    {
                        <p class="card-text text-white">School District: @product.SchoolDistrict</p>
                        <p class="card-text text-white">School District Phone: @product.SchoolDistrictPhone</p>
                        <p class="card-text text-white">High School: @(product.HighSchool != true ? product.HighSchool : "N/A")</p>
                        <p class="card-text text-white">Middle School: @(product.MiddleSchool != true ? product.MiddleSchool : "N/A")</p>
                        <p class="card-text text-white">Elementary School: @(product.ElementarySchool != true ? product.ElementarySchool : "N/A")</p>
                    }
                    <p class="card-text text-white">Facebook: <a href="@(product.FaceLink != null ? product.FaceLink : "")">@(product.FaceLink != null ? product.FaceLink : "N/A")</a> </p>
                    <p class="card-text text-white">Twitter: <a href="@(product.TwitLink != null ? product.TwitLink : "")">@(product.TwitLink != null ? product.TwitLink : "N/A")</a> </p>
                    <p class="card-text text-white">GoogleLink: <a href="@(product.GoogleLink != null ? product.GoogleLink : "")">@(product.GoogleLink != null ? product.GoogleLink : "N/A")</a> </p>
                </div>
            </div>
        </div>
    }
</div>
<a class="btn btn-light fw-bold fs-4" asp-action="Index" asp-controller="Features" asp-route-returnUrl="@ViewData["ReturnUrl"]">Back</a>

src/Presentation/Estate.MVC/Areas/Admin/Views/Features/Index.cshtml
@model PaginationVM<ItemFeaturesVM>

@{
    int count = (Model.CurrentPage - 1) * Model.Take;
}

<div class="d-flex justify-content-end">
    <div class="input-group mx-3">
        <form asp-action="Index" asp-controller="Features"
              asp-route-order="@Model.Order">
            <input type="text" class="form-control" placeholder="Search now" name="search" value="@(Model.Search == null? "":Model.Search)">
        </form>
    </div>
    <form asp-action="Index" asp-controller="Features"
          asp-route-order="@Model.Search" class="my-2 ">
        <select class="form-control form-control-sm rounded-1" onchange="this.form.submit()" name="Order">
            <option selected disabled>Sort by Default</option>
            <option value="1">Name</option>
            <option value="2">Created at</option>
            <option value="3">Name by Descending</option>
            <option value="4">Created at by Descending</option>
        </select>
    </form>
    <a asp-controller="Features" asp-action="DeletedItems" class="btn btn-danger fw-bold fs-6 text-white w-25 m-2">Deleted Features</a>
</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Features table</h4>
            <a asp-controller="Features" asp-action="Create" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-warning fw-bold fs-6 text-white">Create Feature</a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Products
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var Features in Model.Items)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @Features.Name
                                </td>
                                <td>
                                    @Features.Products.Count
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Features" asp-route-id="@Features.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-primary btn-info">
                                        <i class="mdi mdi-pencil text-white"></i>
                                    </a>
                                    @if (User.IsInRole(UserRoles.Admin.ToString()) || User.IsInRole(UserRoles.Moderator.ToString()))
                                    {
                                        <a asp-action="SoftDelete" asp-controller="Features" asp-route-id="@Features.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-danger btn-info">
                                            <i class="mdi mdi-delete text-white"></i>
                                        </a>
                                    }
                                    <a asp-action="Detail" asp-controller="Features" asp-route-id="@Features.Id" asp-route-returnurl="@Context.Request.Path.Value" class="btn btn-primary">
                                        <i class="mdi mdi-open-in-new text-white"></i>
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(Model.CurrentPage <= 1 ? "disabled" : "")"><a class="page-link" asp-route-page="@(Model.CurrentPage -1)" asp-action="Index" asp-controller="Features">Previous</a></li>
                    @for (int i = 1; i <= Model.TotalPage; i++)
                    {
                        <li class="page-item @(Model.CurrentPage == i ? "disabled" : "")"><a asp-action="Index" asp-route-page="@i" asp-controller="Features" class="page-link">@i</a></li>
                    }
                    <li class="page-item @(Model.CurrentPage >= Model.TotalPage ? "disabled" : "")"><a class="page-link" asp-route-page="@(Model.CurrentPage +1)" asp-action="Index" asp-controller="Features">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

src/Presentation/Estate.MVC/Areas/Admin/Views/Features/Update.cshtml
@model UpdateFeaturesVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Feature</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Features" asp-route-returnUrl="@ViewData["ReturnUrl"]" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>